# Generated by Django 5.2.4 on 2025-07-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_questions_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choise',
            old_name='choise_text',
            new_name='choice_text',
        ),
    ]
